language: node_js
node_js:
  - "node"
install:
  - npm install
  - npm i -g now
script:
  - npm run lint
  - yarn run build
deploy:
  provider: script
  skip_cleanup: true
  script: now -t "$NOW_TOKEN" -p
  on:
    branch: master
after_deploy: now ln -t "$NOW_TOKEN"