language: node_js
node_js:
  - "node"
install:
  - npm install
  - npm install now
script:
  - npm run lint
  - yarn run build
deploy:
  provider: script
  skip_cleanup: true
  script:
  - now ./build -t "$NOW_TOKEN" -p
  on:
    branch: feat/deploy-from-travis